import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export const maxDuration = 30;

// Expo Snack public API — no auth needed for creating anonymous snacks
const SNACK_API = 'https://snack.expo.dev/--/api/v2/snack';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: projectId } = await params;

  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { data: project } = await supabase
      .from('projects')
      .select('name, files')
      .eq('id', projectId)
      .eq('user_id', user.id)
      .single();

    if (!project) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    const files = (project.files as Record<string, string>) || {};

    // Build Snack files payload
    // Snack expects: { "filename.js": { type: "CODE", contents: "..." } }
    // It uses .js / .tsx — just pass as-is, Snack handles tsx fine
    const snackFiles: Record<string, { type: 'CODE'; contents: string }> = {};

    // Find entry files — Snack needs App.js as the root or we use expo-router
    // Map expo-router style files to a flat Snack-compatible structure
    for (const [path, content] of Object.entries(files)) {
      // Skip config-only files that Snack doesn't need
      if (path === '.gitignore' || path === 'tsconfig.json') continue;
      snackFiles[path] = { type: 'CODE', contents: content };
    }

    // If no App.tsx / App.js — create a minimal one pointing at the index
    if (!snackFiles['App.tsx'] && !snackFiles['App.js']) {
      const homeContent = files['app/(tabs)/index.tsx'] || files['app/index.tsx'] || '';
      if (homeContent) {
        snackFiles['App.tsx'] = {
          type: 'CODE',
          contents: homeContent,
        };
      }
    }

    // Create snack via Expo API
    const snackPayload = {
      name: project.name,
      description: `Generated by Cordneed`,
      sdkVersion: '51.0.0',
      files: snackFiles,
    };

    const snackRes = await fetch(SNACK_API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(snackPayload),
    });

    if (!snackRes.ok) {
      const errorText = await snackRes.text();
      console.error('[Snack API] Failed:', snackRes.status, errorText.slice(0, 200));
      return NextResponse.json({ error: 'Snack API failed' }, { status: 502 });
    }

    const snackData = await snackRes.json();
    const snackId: string = snackData.id ?? snackData.hashId ?? snackData.snackId ?? '';

    if (!snackId) {
      console.error('[Snack API] No ID in response:', JSON.stringify(snackData).slice(0, 200));
      return NextResponse.json({ error: 'No snack ID returned' }, { status: 502 });
    }

    return NextResponse.json({ snackId });
  } catch (error) {
    console.error('[/api/projects/:id/snack]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
