import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { files, projectName } = await request.json();

    if (!files || typeof files !== 'object') {
      return NextResponse.json({ message: 'Files required' }, { status: 400 });
    }

    // ── Parse dependencies from generated package.json ───────────────────────
    let dependencies = {};
    try {
      if (files['package.json']) {
        const pkg = JSON.parse(files['package.json']);
        dependencies = pkg.dependencies || {};
      }
    } catch (e) {
      console.warn('Could not parse package.json for Snack dependencies', e);
    }

    // ── Format code for Snack API ────────────────────────────────────────────
    const code: Record<string, any> = {};
    for (const [path, content] of Object.entries(files)) {
      if (typeof content === 'string' && !path.startsWith('.') && !path.endsWith('.png')) {
        let transformedContent = content;
        
        // Snack simulator notoriously fails at resolving `@/` aliases defined in tsconfig.
        // We dynamically convert any `@/` import into standard relative paths `../../`
        if (transformedContent.includes('@/')) {
          const depth = path.split('/').length - 1;
          const relativePrefix = depth === 0 ? './' : '../'.repeat(depth);
          transformedContent = transformedContent.replace(/@\//g, relativePrefix);
        }
        
        code[path] = { type: 'CODE', contents: transformedContent };
      }
    }

    // Expo Snack strictly requires an App.js/App.tsx physically present.
    // Since we generate Expo Router apps (which use app/_layout.tsx), we must inject the router bootstrapper.
    if (!code['App.js'] && !code['App.tsx']) {
      code['App.js'] = { type: 'CODE', contents: "import 'expo-router/entry';" };
    }

    const parsedDeps: Record<string, any> = {};
    for (const [key, val] of Object.entries(dependencies)) {
      // Exclude core packages that Expo SDK resolves automatically
      if (['react', 'react-native', 'react-dom', 'react-native-web', 'expo'].includes(key)) continue;
      
      const v = typeof val === 'string' ? val : val?.version;
      // Strip wildcard versions to avoid pulling incompatible unstable packages
      if (v !== '*' && v !== 'latest') {
        parsedDeps[key] = { version: v };
      }
    }

    // Ensure critical Expo Router dependencies are present, overriding AI's versions
    // Wildcard versions pull incompatible Next/React Native Web packages causing 'n.valueOf' crashes.
    dependencies = {
      ...parsedDeps, // AI provided versions
      "expo-router": { version: "~3.4.10" },
      "expo-constants": { version: "~15.4.6" },
      "expo-linking": { version: "~6.2.2" },
      "expo-status-bar": { version: "~1.11.1" },
      "react-native-safe-area-context": { version: "4.8.2" },
      "react-native-screens": { version: "~3.29.0" },
      "@expo/vector-icons": { version: "^14.0.0" },
      "react-native-web": { version: "~0.19.6" },
      "react-dom": { version: "18.2.0" },
      "@expo/metro-runtime": { version: "~3.1.3" },
      "react-native-svg": { version: "14.1.0" }
    };

    // ── Call official Expo Snack API ──────────────────────────────────────────
    const response = await fetch('https://exp.host/--/api/v2/snack/save', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        manifest: {
          name: projectName || 'App',
          description: 'Generated by Cordneed',
          sdkVersion: '50.0.0', // Standard active Expo SDK for Snack
        },
        code,
        dependencies,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[Snack API] Error:', errorText);
      return NextResponse.json({ message: 'Expo Snack API rejected payload' }, { status: 502 });
    }

    const data = await response.json();
    return NextResponse.json({ id: data.id });
  } catch (error) {
    console.error('[/api/snack] Error:', error);
    return NextResponse.json({ message: 'Failed to generate Snack' }, { status: 500 });
  }
}
