import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { files, projectName } = await request.json();

    if (!files || typeof files !== 'object') {
      return NextResponse.json({ message: 'Files required' }, { status: 400 });
    }

    // ── Parse dependencies from generated package.json ───────────────────────
    let dependencies = {};
    try {
      if (files['package.json']) {
        const pkg = JSON.parse(files['package.json']);
        dependencies = pkg.dependencies || {};
      }
    } catch (e) {
      console.warn('Could not parse package.json for Snack dependencies', e);
    }

    // ── Format code for Snack API ────────────────────────────────────────────
    const code: Record<string, any> = {};
    for (const [path, content] of Object.entries(files)) {
      if (typeof content === 'string' && !path.startsWith('.') && !path.endsWith('.png')) {
        code[path] = { type: 'CODE', contents: content };
      }
    }

    // ── Call official Expo Snack API ──────────────────────────────────────────
    const response = await fetch('https://exp.host/--/api/v2/snack/save', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        manifest: {
          name: projectName || 'App',
          description: 'Generated by Cordneed',
          sdkVersion: '50.0.0', // Standard active Expo SDK for Snack
        },
        code,
        dependencies,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[Snack API] Error:', errorText);
      return NextResponse.json({ message: 'Expo Snack API rejected payload' }, { status: 502 });
    }

    const data = await response.json();
    return NextResponse.json({ id: data.id });
  } catch (error) {
    console.error('[/api/snack] Error:', error);
    return NextResponse.json({ message: 'Failed to generate Snack' }, { status: 500 });
  }
}
